version: '3'
services:
  postgres:
    image: postgres:11.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polls
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - 5000:5000
    environment:
      TZ: "Asia/Tokyo"
      PG_USER: "postgres"
      PG_PASS: "postgres"
      PG_HOST: "postgres"
      PG_DB: "polls"